# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 66b6d93c98fce81575bb67350e9ac23b28ad14fe0f90ec38a3b79e9924425140981184994cfdb44beef39d7f8fcc236acc8728d736d0176a40cd00eb3f8246cf

test:
  secret_key_base: 368df6b840d9182911c6310bfc66c32ae5da5a7bb5db2a150a2fa3bb2ef0e6df0aec1ab46f1b877668bd74fccbe7e9cc1a4ef811651f3106c8f9973ad60968c8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
